name: Docker
on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - 'v*'          # matches v0.20.1, v1.0.0 etc
  pull_request:
    branches:
      - master

env:
  IMAGE_NAME: lycheeverse/lychee
  DOCKER_PLATFORMS: linux/amd64,linux/arm64/v8
  DOCKERFILE: Dockerfile-CI.Dockerfile
  DOCKERFILE_ALPINE: Dockerfile-CI.alpine.Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'lycheeverse' &&
        github.actor != 'dependabot[bot]' &&
        ( github.event_name != 'pull_request' || github.event.pull_request.head.repo.owner.login == github.event.pull_request.base.repo.owner.login )
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      # Debian image tags
      - name: Docker meta (debian)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern=v{{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=branch
            type=ref,event=pr
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}

      # Alpine image tags
      - name: Docker meta (alpine)
        id: meta-alpine
        uses: docker/metadata-action@v5
        with:
          flavor: |
            suffix=-alpine
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern=v{{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=branch
            type=ref,event=pr
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}

      # Debug step to see generated tags
      - name: Show tags
        run: |
          echo "Tags for debian: ${{ steps.meta.outputs.tags }}"
          echo "Tags for alpine: ${{ steps.meta-alpine.outputs.tags }}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Image (debian)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ env.DOCKERFILE }}
          platforms: ${{ env.DOCKER_PLATFORMS }}
          push: ${{ (github.event_name != 'pull_request' && github.actor != 'dependabot[bot]) || startsWith(github.ref, 'refs/tags/') }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            LYCHEE_VERSION=${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || (github.ref == 'refs/heads/master' && 'nightly' || 'latest') }}

      - name: Push Image (alpine)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ env.DOCKERFILE_ALPINE }}
          platforms: ${{ env.DOCKER_PLATFORMS }}
          push: ${{ (github.event_name != 'pull_request' && github.actor != 'dependabot[bot]) || startsWith(github.ref, 'refs/tags/') }}
          tags: ${{ steps.meta-alpine.outputs.tags }}
          labels: ${{ steps.meta-alpine.outputs.labels }}
          build-args: |
            LYCHEE_VERSION=${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || (github.ref == 'refs/heads/master' && 'nightly' || 'latest') }}

      - name: Update DockerHub description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: lycheeverse/lychee
          readme-filepath: README.md
